[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true

[theme]
base = "light"
font = "sans serif"
